---
title: "A .Rmd Template for Master's Dissertations at CLSBE"
author: "Antonio Fidalgo"
date: 2022-05-10
description: "This posts introduces... well see title above. I hope it will be helpful for students. Also, feedback is warmly welcome so that the next versions of the template may offer further improvements."
tags: ["template", "thesis", "best practices", "R Markdown", "workflow"]
categories: ["template"]
link-citations: true
ShowToc: true
editPost:
    URL: "https://github.com/AntonioFidalgo/post/blob/main/clsbe-template/index.Rmd"
    Text: "Rmd Source Code \U0001f4ce"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = FALSE)
library(ggplot2)
```


# Motivation  

I have been strongly promoting the use of .Rmd files for research---e.g., [here](https://antoniofidalgo.page/discoveR/why.html){target="_blank"}. This type of file combines text editing---in Markdown language---and data analysis---in R language---in one single document, allowing for reproducible research as well as dynamic documents.^[I'm focusing here on .Rmd because R is our software of choice. But I should mention that there is a restricted list of alternative files that share these features.]   

Overall, the workflow associated with these files sets a high epistemological standard of good practices in science.^[The Master's dissertation is an exercise in scientific investigation. As such, it should abide by the rules of scientific investigation. Logically, I see no reason for students to not use a .Rmd file for their thesis. Incidentally, recalling the scientific nature of the exercise is sufficient to discard the fallacious argument of the "industry-compatibility"---use what is used in the industry. The firm may rationally reject the .Rmd workflow based on a cost-benefit analysis. But this should have no bearing on the choices made at University where other criteria are used.]

It occurred to me that the layout of the Master's dissertation and its conformity with the School's requirements may prevent students from adopting that standard. So I decided to help lift that obstacle by offering a .Rmd template for dissertations at CLSBE.    

As of now, I came up with a beta v.0.1---first draft. I will first gauge if it proves useful and worth maintaining. So I'm putting it out as a work in progress along with a call for comments, suggestions, etc.   

Actually, there are two fronts in this project---for both the **feedback is much welcome**: a template and a manual.

# Download the Template  

The template is a R project, i.e., a bundle of files containing the main .Rmd file. You can download the latest version [here](clsbe-thesis.zip).




# Check out the Manual

An online manual with all sorts of instructions for using the template is also available. Read it [here](https://antoniofidalgo.page/template/){target="_blank"}.  

The manual requires the same credentials as for this blog post.


 
# Try Knit

The file `template.Rmd` should be ready to `Knit` out of the box, albeit slowly at the first attempt.   

Please let me know of your experience.


  








